version: '3.8'
services:
  db:
    image: postgres:15
    container_name: arduino_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: plant_system
    ports:
      - "5432:5432"